import "@/styles/global.css";
import { Metadata } from "next";
import NavBar from "./components/navbar";

export const metadata: Metadata = {
  title: {
    default: "Airui",
    template: "Airui | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background font-sans">
        <div className="relative flex min-h-screen flex-col">
          <NavBar />
          <div className="flex-1">{children}</div>
          <footer className="border-t py-6 md:py-0">
            <div className="container flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row"></div>
          </footer>
        </div>
      </body>
    </html>
  );
}
